### ISSUE TITLE
Multi Currency

### ISSUE THREAD

**Issue by banwood45** [divineuba/dlocal-woocommerce#1]
Please can you make the plugin multi-currency and add a custom input for callback url.
Thanks

**Comment by tomiwataiwo** [comment]
multi-currency would make payment easier for users in different countries

**Comment by banwood45** [comment]
> multi-currency would make payment easier for users in different countries

Exactly my point Mr Tomiwa.  End users or clients can conduct transactions in all of the other countries currencies they own if they have a variety of them.

**Comment by divineuba** [comment]
It has been fixed in the new update

**Comment by divineuba** [comment]
> Please can you make the plugin multi-currency and add a custom input for callback url. Thanks

Thank you for the pointing out the issue
